### ISSUE TITLE
Redirect Flow – deleting orders paid with other gateway (in 3.0.5.21)

### ISSUE THREAD

**Issue by ChristianAF** [bitpay/bitpay-checkout-for-woocommerce#32]
Orders are been deleted or canceled after the 15 minutes exires time though the orders were paid with other gateway.

Steps:
1. try to pay with bitpay first
2. then go back, reload page and pay with other gateway (Example: stripe or Bolt)
3. order will be there on the back end, yet new order emails won’t be sent yet, and order has no order notes
4. in 15 minutes I logged in and order was not in the dashboard, but was on the other gateway end.
5. when the bitpay transaction expires it deletes or cancelles the order (depends the settings) no matter if it’s paid or not. Should not delete or cancel if it’s already paid with other gateway.

**Comment by thejoshualewis** [comment]
Should be resolved in latest (3.4.1911)
