### ISSUE TITLE
Letsencrypt cUrl needs to be installed error

### ISSUE THREAD

**Issue by alialiwa2005** [bitpay/bitpay-checkout-for-woocommerce#37]
I have a newly renewed letsencrypt ssl certificate (4096 bit key) installed.

Bitpay would not install as a woocommerce plug in with error: cURL needs to be installed...

**Comment by thejoshualewis** [comment]
cUrl needs to be installed on your server to make requests.

**Comment by alialiwa2005** [comment]
cURL is installed. 
I'll do a complete reset tomorrow. Will reply with updated information.

**Comment by alialiwa2005** [comment]
Update: Uninstalled cURL, checked for updates/upgrades on Debian, reinstalled cURL. 

Works now. Thank you.
