### ISSUE TITLE
Undefined variable $gateways

### ISSUE THREAD

**Issue by ravihani** [bitpay/bitpay-checkout-for-woocommerce#40]
Getting below errors in TEST mode with test.bitpay.com with WooCommerce plugin. Error log does not show any error and checkout does not work either.  Could someone point me where can i check the error logs or how to resolve this issue? I appreciate the help.

Warning: Undefined variable $gateways in C:\xampp\htdocs\wp\wp-content\plugins\bitpay-checkout-for-woocommerce\index.php on line 566

Warning: Undefined array key "bitpay_checkout_product" in C:\xampp\htdocs\wp\wp-content\plugins\bitpay-checkout-for-woocommerce\index.php on line 569

**Comment by vivianspencer** [comment]
I'm also receiving this error on the checkout, happens in Test & Live mode

`Notice: Undefined variable: gateways in /app/web/app/plugins/bitpay-checkout-for-woocommerce/index.php on line 566 Notice: Undefined index: bitpay_checkout_product in /app/web/app/plugins/bitpay-checkout-for-woocommerce/index.php on line 569`

Checkout is working though.
